# Variaveis para serem usadas nos scripts
# Podem ser actyalizadas a qualquer momento

# URL para o ficheiro PDF da contratualizacao dos CSP 2023
url_pdf_contratualizacao = "https://www.acss.min-saude.pt/wp-content/uploads/2016/10/Operacionalizacao_CSP_2023_VF.pdf"

# paginas inicio e fim de 
pagina_inicial_MATRIZ_MULTIDIMENSIONAL = 60
pagina_final_MATRIZ_MULTIDIMENSIONAL = 62


# id dos indicadores iniciais e finais para extração automática do sdm
sdm_indicador_inicial = 1
sdm_indicador_final = 448

